### ISSUE TITLE
error: expected ident, found #

### ISSUE THREAD

**Issue by robbat2** [rust-lang-nursery/bitflags#138] opened 2017-11-28 01:06 UTC
```
error: expected ident, found #
   --> /home/robbat2/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/lib.rs:423:29
    |
423 |                               #[allow(deprecated)]
    |                               ^
    | 
   ::: /home/robbat2/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/example_generated.rs
    |
4   | / bitflags! {
5   | |     /// This is the same `Flags` struct defined in the [crate level example](../index.html#example).
6   | |     /// Note that this struct is just for documentation purposes only, it must not be used outside
7   | |     /// this crate.
...   |
13  | |     }
14  | | }
    | |_- in this macro invocation

Build failed, waiting for other jobs to finish...
error: failed to compile `s3lsio v0.1.21`, intermediate artifacts can be found at `/tmp/cargo-install.7Y1euTb11RKT`

Caused by:
  Could not compile `bitflags`.
```

**Comment by naccib** [comment] 2017-11-28 13:40
I have the same error.

OS: Ubuntu 16.04
Cargo Version: `cargo 0.23.0 (61fa02415 2017-11-22)`
Compiler Version: `rustc 1.22.1 (05e2e1c41 2017-11-22)`

It happens both with the `stable` and the `nightly` toolchains.

**Comment by dtolnay** [comment] 2017-11-28 15:15
Bitflags 1.0.1 requires rustc >=1.20.0. I believe that error is from rustc 1.18.0 or 1.19.0.

**Comment by naccib** [comment] 2017-11-28 16:27
@dtolnay This is still happening to me with `rustc >= 1.20.0`.

**Comment by dtolnay** [comment] 2017-11-28 19:05
@naccib do the following commands reproduce the error for you?

```
git clone https://github.com/rust-lang-nursery/bitflags
cd bitflags
rustup update 1.20.0
cargo +1.20.0 build
```

Separately, same question for +1.21.0 and +1.22.1.

**Comment by naccib** [comment] 2017-11-28 20:31
It works with `1.20.0` and I found why it does not works in my case.

When installing from my project, I still get the error.
Running `sudo cargo install` with the `--verbose` flag, it adds the following information:
```Caused by:
  process didn't exit successfully: `rustc --crate-name bitflags /home/naccib/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg feature="default" --cfg feature="example_generated" -C metadata=f9ca8c19181c7f4f -C extra-filename=-f9ca8c19181c7f4f --out-dir /home/naccib/play/rgba-sound/target/release/deps -L dependency=/home/naccib/play/rgba-sound/target/release/deps --cap-lints allow` (exit code: 101)
```

The thing is, `rustc` version is `1.20.0`, but `sudo rustc` version is `1.17.0`. 
I will try to fix this.

**Comment by dtolnay** [comment] 2017-11-28 20:57
Sounds good. I am closing this issue because we don't plan to support <1.20.0.

**Closed by dtolnay** 2017-11-28 20:57 UTC

**Comment by reedhedges** [comment] 2018-01-04 16:48
> The thing is, rustc version is 1.20.0, but sudo rustc version is 1.17.0.

Remove `rustc` package from Ubuntu   (and `cargo`) so it isn't confused with manually installed  newer version.
