### ISSUE TITLE
Error building libucl-sys

### ISSUE THREAD

**Issue by yohanesu75** [rust-lang-nursery/bitflags#46] opened 2016-04-12 02:25 UTC
bitflags 0.3 builds fine but 0.5 gives me this error when building libucl-sys  (latest: https://github.com/hauleth/libucl-sys). Not sure where the problem is..

```
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
lib.rs:89:1: 99:2 note: in this expansion of bitflags! (defined in <bitflags macros>)
lib.rs:91:31: 91:36 help: run `rustc --explain E0412` to see a detailed explanation
lib.rs:91:31: 91:36 help: you can import several candidates into scope (`use ...;`):
lib.rs:91:31: 91:36 help:   `bitflags::__core::os::raw::c_int`
lib.rs:91:31: 91:36 help:   `libc::c_int`
lib.rs:91:31: 91:36 help:   `std::os::raw::c_int`
lib.rs:91:31: 91:36 error: type name `c_int` is undefined or not in scope [E0412]
lib.rs:91     flags ucl_object_flags_t: c_int {
```

**Comment by dimbleby** [comment] 2016-04-21 12:27
Another duplicate of #39, isn't it?

**Comment by nox** [comment] 2016-05-16 14:16
This can be closed now.

**Closed** 2016-05-16 16:32 UTC
